server:
  port: 7000

spring:
  datasource:
    druid:
      url: jdbc:mysql://10.110.74.20:3306/oauthdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 0
    cache: false

  redis:
    database: 7
    host: 10.110.74.29
    port: 6379
    password: redis123456aB

custom:
  access-token:
    expires-hour: 2
  refresh-token:
    expires-day: 7
  wechat:
    appId: "wxe480247fb8329918"
    secret: "9bda0ae78f513dbafbf984f8b3618758"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
